name: Create release

on:
  push:
      branches: master
      tags:
        - '*'

jobs:
  release:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install ZIP
          uses: montudor/action-zip@v1

        - name: ZIP assets
          run: zip -qqr ../ha-enever-${{ github.ref_name }}.zip ./enever/ -x "*/__pycache__/*"
          working-directory: custom_components

        - name: Create release
          uses: softprops/action-gh-release@v2
          with:
            draft: false
            prerelease: false
            files: ha-enever-*.zip